### ISSUE TITLE
Tech to use for Unit testing and test coverage checks in reactjs.

### ISSUE THREAD

**Issue by aguzmans** [Sesame-Disk/cool-storage-microfrontend#1]
Find a test coverage checks tool that tells us if everything has unit tests or not and help use write better tests.

Expected result:
1- Documentaiton of how to do unit testin (can a short explanaton with links to specifics written in other places or wrtten by your self)
2- Possible test coverage libraries/framewords to use. Recommend and explain one and test  and how results; document same way as point 1.

**Comment by alvaldes** [comment]
# Solution 1: 
`Tests Library | Jest | Jest DOM`

## Installation

  - ### Step 1: Install the dependencies
    - #### Install [Test Library](https://testing-library.com/docs/react-testing-library/intro)

      `npm i --save-dev @testing-library/react`

    - #### Install [Jest](https://jestjs.io)
    
      `npm i --save-dev jest`

    - #### Install [Jest DOM](https://github.com/testing-library/jest-dom)

      `npm install --save-dev @testing-library/jest-dom`

    

  - ### Step 2: Config Jest and set package.json to use Jest
    - #### Initialize Jest
    
      `npm run jest --init`
      
      And set the following configs:
      >Would you like to use Jest when running your "test" script in "package.json"? > (y/n): yes

      >Choose the test environment that will be used for testing: > jsdom (browser-like)

      >Do you want Jest to add coverage reports? > no

      >Which provider should be used to instrument the code for coverage? > babel

      >Automatically clear mock calls and instances between every test? > no

    - ### In package.json add the following:

      `"scripts": {
        "test": "jest",
        "test:watch": "jest --watch"
      }`

  - ### Step 3: Code Coverage Config
    * Add to the package.json file:
  
      `{
        "coverage": "jest --collect-coverage"
      }`


  - ### Notes:
    - If we will be using css modules we need to add the following to the config:
      >Install [jest-css-modules](https://www.npmjs.com/package/jest-css-modules):
      `npm i --save-dev jest-css-modules`

      >Set the following to the jest.config.js file:
      `{
         "jest": {
               "moduleNameMapper": {
               "\\.(css|less|scss|sss|styl)$": "<rootDir>/node_modules/jest-css-modules"
         }
      }
}`

## Reference
- Part 1: Building the Actual React Tabbed Component - https://www.youtube.com/watch?v=DWCCkcJgvf0
- Part 2: Intro to Testing - https://www.youtube.com/watch?v=kwgJXh6yQmQ
- Part 3: Setting up our Testing Environment - https://www.youtube.com/watch?v=lmlGDFZzYmo
- Part 4: Writing Unit Tests - https://www.youtube.com/watch?v=OaMzkeUgZa8
- Part 5: Testing our React Component - https://www.youtube.com/watch?v=c31KJTzt5YY&t=1s
- Part 6: Looking at Code Coverage - https://www.youtube.com/watch?v=3R0UkXyS5us

**Comment by alvaldes** [comment]
# Solution 2: 
`Jest | Enzyme`

## Installation

  - ### Step 1: Install the dependencies
    - #### Install [Jest](https://jestjs.io)
    
      `npm i --save-dev jest`

    - #### Install [Enzyme](https://enzymejs.github.io/enzyme/)

      `npm i-save-dev enzyme`

    

  - ### Step 2: Config Jest and set package.json to use Jest
    - ### In package.json add the following:

      `"scripts": {
        "test": "jest",
        "test:watch": "jest --watch"
      }`

  - ### Step 3: Code Coverage Config
    * Add to the package.json file:
  
      `{
        "coverage": "jest --collect-coverage"
      }`

## Reference
- Unit Testing in React using Jest and Enzyme - https://www.vtnetzwelt.com/web/unit-testing-in-reactjs-using-jest-enzyme/
- How to (unit) test in React - https://itnext.io/how-to-unit-test-in-react-72e911e2b8d
- Unit Testing in ReactJS using Jest and Enzyme - https://dzone.com/articles/unit-testing-in-reactjs-using-jest-and-enzyme

**Comment by alvaldes** [comment]
## React-testing-library vs Enzymejs

While Enzyme has been around for a long time now (released back in 2015), react-testing-library was released more recently (2018) and gained a lot of traction quickly. Ok let's bring some numbers:
- According to its page on GitHub [@Enzymejs](https://github.com/enzymejs/enzyme)
   - 270 Watch
   - 366 Contributors
   - 2.1k Fork
   - 19.9k Stars 
   - used by more than 406k users
- In the meantime [@react-testing-library](https://github.com/testing-library/react-testing-library) has:
   - 144 Watch
   - 163 Contributors
   - 940 Fork
   - 16.3k Stars
   - used by more than 4.3m users

With react-testing-library, you’re able to easily write tests that represent well enough how the application is experienced by users. On the other hand, when you’re writing your tests with Enzyme, even though you are also able to achieve the same level of confidence that you might get with react-testing-library, it is a bit more cumbersome to build your test structure in a way that resembles a real user. In general, what you might see in codebases when looking at tests with Enzyme is that you’re actually testing the props and state of your components, meaning you are testing the internal behavior of components to confirm that the correct view is being presented to users.
[Create React App](https://create-react-app.dev/docs/running-tests) uses [Jest](https://jestjs.io/) as its test runner and suggests using react-testing-libary to test individual components for unit, integration and end-to-end test.

> Also 4.3 million people can't be wrong about that right?

#### Initialize a Create React App Project
`npm install`

#### Project Structure
└─ cool-storage-microfrontend
│    └─ node_modules
│   ├─ public
│   │  ├─images
│   │  ├─videos
│   │  ├─misc
│   ├─ src
│   │ └─ components
│   │ │  └─layouts
│   │ ├─ libs     //third party libraries
│   │ ├─ pages
│   │ ├─App.js
│   │ ├─App.test.js
│   │ ├─index.css
│   │ ├─index.js
