### ISSUE TITLE
How to make the interface multi lenguague?

### ISSUE THREAD

**Issue by aguzmans** [Sesame-Disk/cool-storage-microfrontend#11]
We need this software to support initially English and spanish, but we need to be able to add multiple translations on the way, for instance all the major languages will be required if we grow.

Objective is to determine: 

1. What are the options.
2. Choose/recommend one of those and explain the reasoning behind it.

Story points: 2

**Comment by alvaldes** [comment]
## Found 2 options for internationalizations in React:
1- [i18next](https://www.i18next.com/)
2- [Format.JS](https://formatjs.io/)

### Some Stats
#### Their respective libraries for React
![image](https://user-images.githubusercontent.com/44712690/167200802-20ab0340-1203-4586-9dee-61ba92246c6a.png)

### Download Graph (1 Year)
![image](https://user-images.githubusercontent.com/44712690/167209929-f6e8c208-aeea-40ba-8db7-b80b021f90c1.png)

### Recommend - i18next && react-i18next library
i18next provides:
* Flexible connection to [backend](https://www.i18next.com/overview/plugins-and-utils#backends) (loading translations via xhr, ...)
* Optional [caching](https://www.i18next.com/how-to/caching), user [language detection](https://www.i18next.com/overview/plugins-and-utils#language-detector), ...
* Proper [pluralizations](https://www.i18next.com/translation-function/plurals)
* Translation [context](https://www.i18next.com/translation-function/context), [Nesting](https://www.i18next.com/translation-function/nesting), [Variable replacement](https://www.i18next.com/translation-function/interpolation)
* Flexibility: [Use it everywhere](https://www.i18next.com/overview/supported-frameworks)
* Extensibility: eg. [sprintf](https://www.i18next.com/overview/plugins-and-utils#post-processors)

## Reference
* [react-i18next VS React Intl](https://www.libhunt.com/compare-react-i18next-vs-formatjs)
* [npm Trends - i18next vs Format.JS](https://www.npmtrends.com/i18next-vs-react-i18next-vs-react-intl-vs-intl-messageformat)

**Comment by aguzmans** [comment]
Good job @alvaldes,
Please create an issue to get started with Spanish and english (default). Feel free to create the issue, story points and ask any further questions you might have. This issue is to be done once we have the prototype, make sure you mention that too. and then close this one.
