### ISSUE TITLE
Inefficient Regular Expression Complexity in nth-check #1

### ISSUE THREAD

**Issue by aguzmans** [Sesame-Disk/cool-storage-microfrontend#14]
Low priority, analyze in the future.

Objective(s): 
1. Review why it's happening.
2. Install a fix if possible, but the fix should not break the software as this is not a very vulnerable issue.

Inefficient Regular Expression Complexity in nth-check #1: https://github.com/Sesame-Disk/cool-storage-microfrontend/security/dependabot/1

Story points: 1

**Comment by alvaldes** [comment]
As was explain in [this](https://github.com/facebook/create-react-app/issues/11174) issue, it is (very likely) a false alarm and can be safely dismissed.

More specifically, we are using CRA and nth-check is referenced only from it. CRA is a build tool and the vulnerable code will never get into the resulting application bundle and thus will never be called by client code.

### Fix it [here](https://github.com/Sesame-Disk/cool-storage-microfrontend/commit/55c9a01979b959f9c9eeea04d349f38ab6c31749) using:
1- Add this to the `package.json`:
```
{
  "overrides": {
    "nth-check": "^2.0.1"
  },
}
```
2- Run `npm install`
3-  Then you can run `npm audit` to found vulnerabilities (and to check if this one was fixed)
