### ISSUE TITLE
Define Settings page details 

### ISSUE THREAD

**Issue by alvaldes** [Sesame-Disk/cool-storage-microfrontend#23]
#### Here are some of the settings field 👇
> *Pending:* still needs to be purged to include the actual user settings

![image](https://user-images.githubusercontent.com/44712690/170062169-5a0adaf2-d480-45c7-80f7-ce2bba1c1b5c.png)
![image](https://user-images.githubusercontent.com/44712690/170062306-57269036-4c67-4f4c-a688-bcd96d65b69e.png)

Story Points: 2

**Comment by abelguzman** [comment]
Could you please add some examples of what those elements are in the description?

**Comment by alvaldes** [comment]
Here are some of the settings field 👇
> *Note:* still needs to be purged to include the actual user settings

![image](https://user-images.githubusercontent.com/44712690/170062169-5a0adaf2-d480-45c7-80f7-ce2bba1c1b5c.png)
![image](https://user-images.githubusercontent.com/44712690/170062306-57269036-4c67-4f4c-a688-bcd96d65b69e.png)

**Comment by alvaldes** [comment]
Closed here https://github.com/Sesame-Disk/cool-storage-microfrontend/commit/cd47330027df97bfbe3f893faf9208afab463012
