### ISSUE TITLE
Change a few links in the prototype.

### ISSUE THREAD

**Issue by aguzmans** [Sesame-Disk/cool-storage-microfrontend#25]
Small issues to fix by redirecting each of those features to this links:
1. This should be changed to Cool Storage by NiHao Cloud and have a link to [sesamedisk.com](https://sesamedisk.com/)
2. [Forgot password?](https://app.nihaoconsult.com/accounts/password/reset/)
2. [Privacy Policy](https://www.nihaocloud.com/privacy-policy/)
3. [Terms of Service](https://www.nihaocloud.com/privacy-policy/#terms_of_service)
4. [Sign Up](https://sesamedisk.com/register/)
5. [About](https://sesamedisk.com/about/)

Story point: 1

**Comment by alvaldes** [comment]
closed here https://github.com/Sesame-Disk/cool-storage-microfrontend/commit/bfbc3f261f1e477735ea59654585f89a1cafc505
