### ISSUE TITLE
Implement functional prototype of uploads (multiparts)

### ISSUE THREAD

**Issue by aguzmans** [Sesame-Disk/cool-storage-microfrontend#30]
Make the upload work with the API.
This needs to implement the multipart upload from seafile in tha api docs find the "Upload File in Chunks" section of this page: https://download.seafile.com/published/web-api/v2.1/file-upload.md

Here are some libraries that implement similar things using JS: 

1. https://github.com/muxinc/upchunk
2. https://github.com/Buzut/huge-uploader
3. https://medium.com/swlh/uploadig-large-files-as-chunks-using-reactjs-net-core-2e6e00e13875

You need to find the best way and implement that using the seafile standard.

Story points: 3

**Comment by alvaldes** [comment]
Initial approach to the upload feature in this commit edddda60d6766e9e97dbadd0afabaeff1a0750a3
* A new interface 
* Connect to the API and send files via http request 
* Capture the upload percentage
