### ISSUE TITLE
Implementar multipar uploads en el FE, using the existing feature from the backend.

### ISSUE THREAD

**Issue by aguzmans** [Sesame-Disk/cool-storage-microfrontend#31]
For now use the upload available for you from the backend, no need to make it compatible with seafile just yet.

This needs to implement the multipart upload same as the seafile in api docs find the "Upload File in Chunks" section of this page: https://download.seafile.com/published/web-api/v2.1/file-upload.md

The front end then needs to implement a call of that method using one of these ways or something similar:

https://github.com/muxinc/upchunk
https://github.com/Buzut/huge-uploader
https://medium.com/swlh/uploadig-large-files-as-chunks-using-reactjs-net-core-2e6e00e13875

Story points: 5

**Comment by alvaldes** [comment]
closed [here](https://github.com/Sesame-Disk/cool-storage-microfrontend/pull/35/commits/4b3ec5619c9af6956ffc50ca3b80aea578a8117a)
