### ISSUE TITLE
Design the layout of the system libraries to use for styling, menu design etc, site layout in reactJS+HTML+CSS.

### ISSUE THREAD

**Issue by aguzmans** [Sesame-Disk/cool-storage-microfrontend#4]
The objective is to Give it the feel of a real system and will be used as the base to continue developing and give it functionality in the near future.

Story points: 2

**Comment by alvaldes** [comment]
## My proposal:

### Stack
   - [<img src="https://img.shields.io/badge/Nextjs-v12.1-blue.svg?logo=LOGO">](<https://nextjs.org/>)
   * [<img src="https://img.shields.io/badge/MUI-v5.6.3-blue.svg?logo=LOGO">](<https://mui.com/>)

### Description
**Next.js** is the React framework for production, which comes with many features like pre-pathing, smart bundling, and no configuration required.
**MUI** is a UI library that provide a intuitive suite of tools based in Google Material Design. Is a fast way to introduce new features to the project.

 ### Project Structure
          └─ microfrontend
              └─ node_modules
              ├─ libs     //third party libraries
              ├─ components
              │  └─layouts
              ├─ styles   //system-specific styles
              ├─ pages
              │  ├─app.js
              │  ├─_document.js
              │  ├─index.js
              ├─ public
              │  ├─images
              │  ├─videos
              │  ├─misc
