### ISSUE TITLE
Non-fuctional Reactjs+HTML+CSS prototype

### ISSUE THREAD

**Issue by aguzmans** [Sesame-Disk/cool-storage-microfrontend#5]
Objectives:

1. Create the forms and fir them on the design.
> login.
> upload page.
> List files page.
> move from/to NiHao Cloud.
This is enough for now, but will require more work in the near future.

The issue depends on: https://github.com/Sesame-Disk/cool-storage-microfrontend/issues/4

Story points: 3

**Comment by alvaldes** [comment]
close https://github.com/Sesame-Disk/cool-storage-microfrontend/commit/8aa47299204539123d8c9436090470b6ac00f046
